export const initialTableState = [
    [
        { id: 'a1', canPlay: false, figure: 'T', owner: 'white' },
        { id: 'b1', canPlay: false, figure: 'K', owner: 'white' },
        { id: 'c1', canPlay: false, figure: 'L', owner: 'white' },
        { id: 'd1', canPlay: false, figure: 'DA', owner: 'white' },
        { id: 'e1', canPlay: false, figure: 'KR', owner: 'white' },
        { id: 'f1', canPlay: false, figure: 'L', owner: 'white' },
        { id: 'g1', canPlay: false, figure: 'K', owner: 'white' },
        { id: 'h1', canPlay: false, figure: 'T', owner: 'white' },
    ],
    [
        { id: 'a2', canPlay: false, figure: 'P', owner: 'white' },
        { id: 'b2', canPlay: false, figure: 'P', owner: 'white' },
        { id: 'c2', canPlay: false, figure: 'P', owner: 'white' },
        { id: 'd2', canPlay: false, figure: 'P', owner: 'white' },
        { id: 'e2', canPlay: false, figure: 'P', owner: 'white' },
        { id: 'f2', canPlay: false, figure: 'P', owner: 'white' },
        { id: 'g2', canPlay: false, figure: 'P', owner: 'white' },
        { id: 'h2', canPlay: false, figure: 'P', owner: 'white' },
    ],
    [
        { id: 'a3', canPlay: false, figure: '' },
        { id: 'b3', canPlay: false, figure: '' },
        { id: 'c3', canPlay: false, figure: '' },
        { id: 'd3', canPlay: false, figure: '' },
        { id: 'e3', canPlay: false, figure: '' },
        { id: 'f3', canPlay: false, figure: '' },
        { id: 'g3', canPlay: false, figure: '' },
        { id: 'h3', canPlay: false, figure: '' },
    ],
    [
        { id: 'a4', canPlay: false, figure: '' },
        { id: 'b4', canPlay: false, figure: '' },
        { id: 'c4', canPlay: false, figure: '' },
        { id: 'd4', canPlay: false, figure: '' },
        { id: 'e4', canPlay: false, figure: '' },
        { id: 'f4', canPlay: false, figure: '' },
        { id: 'g4', canPlay: false, figure: '' },
        { id: 'h4', canPlay: false, figure: '' },
    ],
    [
        { id: 'a5', canPlay: false, figure: '' },
        { id: 'b5', canPlay: false, figure: '' },
        { id: 'c5', canPlay: false, figure: '' },
        { id: 'd5', canPlay: false, figure: '' },
        { id: 'e5', canPlay: false, figure: '' },
        { id: 'f5', canPlay: false, figure: '' },
        { id: 'g5', canPlay: false, figure: '' },
        { id: 'h5', canPlay: false, figure: '' },
    ],
    [
        { id: 'a6', canPlay: false, figure: '' },
        { id: 'b6', canPlay: false, figure: '' },
        { id: 'c6', canPlay: false, figure: '' },
        { id: 'd6', canPlay: false, figure: '' },
        { id: 'e6', canPlay: false, figure: '' },
        { id: 'f6', canPlay: false, figure: '' },
        { id: 'g6', canPlay: false, figure: '' },
        { id: 'h6', canPlay: false, figure: '' },
    ],
    [
        { id: 'a7', canPlay: false, figure: 'P', owner: 'black' },
        { id: 'b7', canPlay: false, figure: 'P', owner: 'black' },
        { id: 'c7', canPlay: false, figure: 'P', owner: 'black' },
        { id: 'd7', canPlay: false, figure: 'P', owner: 'black' },
        { id: 'e7', canPlay: false, figure: 'P', owner: 'black' },
        { id: 'f7', canPlay: false, figure: 'P', owner: 'black' },
        { id: 'g7', canPlay: false, figure: 'P', owner: 'black' },
        { id: 'h7', canPlay: false, figure: 'P', owner: 'black' },
    ],
    [
        { id: 'a8', canPlay: false, figure: 'T', owner: 'black' },
        { id: 'b8', canPlay: false, figure: 'K', owner: 'black' },
        { id: 'c8', canPlay: false, figure: 'L', owner: 'black' },
        { id: 'd8', canPlay: false, figure: 'DA', owner: 'black' },
        { id: 'e8', canPlay: false, figure: 'KR', owner: 'black' },
        { id: 'f8', canPlay: false, figure: 'L', owner: 'black' },
        { id: 'g8', canPlay: false, figure: 'K', owner: 'black' },
        { id: 'h8', canPlay: false, figure: 'T', owner: 'black' },
    ],
];
